data:
  image: ubuntu:latest
  volumes:
    - /var/lib/mysql
  command: "true"

mysql:
  restart: always
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: munkireport
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
  volumes_from:
    - data
  ports:
    - "3306:3306"

import_db:
  image: mysql:latest
  links:
    - mysql
  working_dir: /code
  command: sh import_db.sh
  environment:
    - IMPORT_DATABASE=db.sql
  volumes:
    - ./code:/code
    - .:/tmp

mr:
  restart: always
  image: hunty1/munkireport-docker
  environment:
    MYSQL_ROOT_PASSWORD: root
    DB_NAME: munkireport
    DB_USER: admin
    DB_PASS: admin
    DB_SERVER: ${DOCKER_MACHINE_IP}
    # Not possible yet with docker-compose?
    # DB_SERVER: ${MYSQL_PORT_3306_TCP_ADDR}
    MR_SITENAME: "Local tests"
  links:
    - mysql
  ports:
    - "80:80"
